
default: &default
  adapter: mysql2
  encoding: utf8
  username: root
  password:

development:
  <<: *default
  database: lucro_na_moda_development

test:
  <<: *default
  database: lucro_na_moda_test